[package]
name = "pli_tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
fern = "0.7.0"
log = "0.4.22"
regex = "1.7" 


[lib]
name = "pli_tokenizer"
path = "src/lib.rs"  # Declare the library entry point

